language: python
python:
  - '2.7'
  - '3.3'

install:
  - 'travis_retry pip install -e ".[mysql]" --use-mirrors'
  - 'travis_retry pip install coveralls --use-mirrors'

script: 'py.test --pep8 --cov alchemist'

after_success: 'coveralls'
